language: python
dist: xenial
sudo: false

python:
  - "2.7"
  - "3.6"

env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
    # EXAPWD6
    - secure: "CjjG4X6TJpeCwDvXSQnfwvev4FpDFClHhD4gkdMF7go5rookqQzBH4wzWy5bB0L2zsoEDV+EtmkB/v9CxQa3DLVthBGlzXZ9zOxBsD1LJ8Wr9YWnOiVMOnb3KKG1uWBGu0+XLGdUlXFQu/wFUUuvR+D1wARo+Mq81B+jGZv+OB4="
    # EXAUID6
    - secure: "Diw0AgGIbjd7WvD7B9HA2npPpXmgDgQBaU0dXWy1qGG5X4ZNVc0vmlviYLyUT3et1pHgGsoxXFa7P5KDPGNnh5Ni3vkQZ47epznooGvRI3fx5McCrNZb4YrfbX/R6EJzdLiY+yAurQ/kcCUdU6buEXWOwU0Vx/Os042zcfqYWtY="
    # EXAHOST6
    - secure: "OwYWkuDMxvBmKTpSP4ZZdpZlPmF1Nnu+eeimB4KlUmfU89FFf/tyUkr7CR27BxyIMB1VC5Gms6ukJS0A+0rGYkOj3p2lwIo+ymaE28g+KdbglQ2gh72xxkoIeJP3ujOZNqTGyU6Sibt+ORHlt99s3+WTorVLwZh3iSHjmFqovcc="
  matrix:
    # EXASOL 6
    - TESTDB="exa+pyodbc://${EXAUID6}:${EXAPWD6}@${EXAHOST6}/TEST?CONNECTIONLCALL=en_US.UTF-8&DRIVER=EXAODBC" EXTRA_REQUIREMENTS=""
    - TESTDB="exa+turbodbc://${EXAUID6}:${EXAPWD6}@${EXAHOST6}/TEST?CONNECTIONLCALL=en_US.UTF-8&DRIVER=EXAODBC" EXTRA_REQUIREMENTS="-r requirements_extras.txt"

addons:
  apt:
    packages:
      python3-dev
      python-dev
      unixodbc
      unixodbc-dev
      libboost-date-time-dev
      libboost-locale-dev
      libboost-system-dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt $EXTRA_REQUIREMENTS
  - pip freeze
  - pip install coveralls

before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214lv1.so >> odbcconfig/odbcinst.ini

script:
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy_exasol --dburi "${TESTDB}"

after_success:
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini

before_deploy:
  - sudo pip install twine
  - sudo pip install urllib3[secure]

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_upload_docs: true
  user: BY-jk
  password:
    secure: IWn0cBNuEmEJoLv7Va12f5wk4jfL8E036n0EnBRy6ARwnZL/67fe8MFlTrM2MyaFCW7oDba8vEJNgA7SfZXyEQhV4KH+aUvx42M0XNKGq5GY8M6y5AXAhtV45+3PbrAatd8sV/kYbCZySjvneJn4ldvTKgFsaXyF+nK7ZbJ0/GE=
  on:
    branch: master
    tags: true
    python: '3.6'
    condition: ${EXTRA_REQUIREMENTS} > 0
    repo: blue-yonder/sqlalchemy_exasol
